apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "aggregation-service.name" . }}
    chart: {{ include "aggregation-service.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "aggregation-service.fullname" . }}-config
data:
  application.properties: |+
{{- if .Values.configmap }}
    # User-supplied configuration:
{{ .Values.configmap | indent 4 }}
{{- end }}
