{{- if .Values.registryAuth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registryAuth.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{- end -}}